# Site
name: 'Emergency Ventilators'
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/emergency-ventilators'
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Amod:
      name:           Amod Hulge
      site:           https://www.qrera.in
      avatar:         /assets/images/avatar1.jpg
      bio:            "Founder and Director, Qrera Technologies Pvt. Ltd."
      email:          amod.hulge@qrera.in
      twitter:        https://twitter.com/wowthemesnet

    Aditya:
      name:           Aditya Wagh
      site:           http://www.adityawagh.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "Post-doctoral Researcher at IISc, Bangalore. Loves making machines and doing science!"
      email:          waghaditya@gmail.com
      twitter:        https://twitter.com/Aditya_A_Wagh
      
    Santanu:
      name:           Santanu
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "Assist. Prof."
      email:          
      twitter:        

    Abhishek:
      name:           Abhishek
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "Research Student"
      email:          
      twitter:     
      
    Shwetha:
      name:           Shwetha
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "INSPIRE Faculty, IISc, Bangalore"
      email:          
      twitter:     
      
    Pradeep:
      name:           Pradeep
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "Assist. Prof."
      email:          
      twitter: 
      
    Priyanka:
      name:           Priyanka
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "Research Student, IISc, Bangalore"
      email:          
      twitter:  
      
    Krishna:
      name:           Krishna
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "Research Student, IISc, Bangalore"
      email:          
      twitter:  
      
    Vineeth:
      name:           Vineeth MP
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "Post-doctoral Researcher"
      email:          
      twitter:
      
     Ruchika:
      name:           Ruchika
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "Researcher"
      email:          
      twitter:
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
